language: php

php:
  - 7.0

env:
  - TRAVIS_NODE_VERSION="6"

cache:
  yarn: true
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

sudo: false

install:
    - composer install --prefer-dist
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn
    # - npm install --no-optional
    - yarn
    - cp .env.travis .env
    - chmod -R o+w storage/
    - mysql -e 'create database trip2;'
    - php artisan migrate:refresh

script:
    - phpunit

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5